### PR TITLE
feat: allow to license any company, add broadcaster license support and flexible licenses

### LINKED ISSUE #127: Register Broadcasters/PSS and allow them to set prices
Broadcasters (PSS, Cinemas etc) should be able to register in the system to be able to participate in the waterfall and set prices.

## Scope
- on Register screen:
   - add "Broadcaster" option to "Type of Role" field
- Broadcaster undergoes same KYC/approval process as all the other companies 
- on the movie License page:
  - RH/distributor should be able to create one or more licenses for the Broadcasters of the movie
  - Broadcaster license as well as a Sales/Distributor licenses may be optionally restricted to a territory/medium/timeframe
  - Broadcaster license only allows the Broadcaster to set the movie price (within their license scope)

## Prerequisites

#93 should be implemented

## Roles

gardener: @troggy 50 DAI
worker: @troggy 250 DAI
reviewer: [reviewer] 50 DAI

### LINKED ISSUE #151: Licensing: allow non-KYC company
> Let's ensure that Main RH may assign a non KYC sub-licensee and the non-KYC sub-licensee may operate as a licensee, but the KYC must happen to receive funds (I assume that might hold up all fund payment from SC)

Proposed solution:
- RH will be able to select ANY company (as of TMDB) for the license. This way we are not blocking RH from creating the license structure in RFR.
- RH will have to select the type of License (see screenshot sketch)
- Disregarding if the company already has licenses in RFR or not, a Sales company will have to undergo the usual KYC process in order to work in RFR Portal.

image

## Scope
- on Sublicense form:
  - add "Type of License" radio button group (See screenshot example, it is a sketch not a final design)
  - change company select box to the search box like on Register Form
  - when submitted create a non-approved Company for non-existing licensees
  - when creating a license save type of license as an attribute of the License
- on Register Form:
  - for SALES companies show the list of movies licensed in RFR instead of the list from TMDB. Rationale: we can get only movies by _production company_ from TMDB, so for Sales this list will always be empty or irrelevant.
  - if the Company already exists and is not approved assign the user to it
  - reject submission, if the Company already exists and is approved;
- on Admin screen:
  - don't show approve/reject buttons for the Sales companies which have no user assigned yet (ie not onboarded yet). Prevent approval of such companies on the backend as well.
- when checking for permissions, use type of licenses instead of type of company everywhere. Both on the frontend and the backend

## Roles
gardener: @troggy 100 DAI
worker: @troggy 720 DAI
reviewer: [reviewer] 80 DAI

### PR DESCRIPTION
**Pull request by troggy**
Please remember the [Contributing Guidelines](https://WhiteRabbitTheWorldIsYours/dashboard/blob/master/CONTRIBUTION.md) :heart:

## What does this PR do?

- allows to search for any company on License Form
- allows to enter any company on License Form even if it is not found in TMDB (same as on Register Form)
- allow registering user for already created companies. This will be allowed only in the company is not yet approved
- introduce the notion of "License Feats". These are the capabilities the license allows .Currently available feats are: "setPrice", "createLicense", "claimRevenue". These are used to control the UI (hide not-allowed things) and to authorize actions on the backend (see requireFeats helper in resolvers)
- added license feat presets on License Form: Distribution, Sales, Broadcaster with the explainer
- improved view of Admin page
- refactored dashboard-commons: split modesl into separate files, moved common license related code there from backend

## Recommendations for testing
- verify producer is able to add the movie
- verify producer can add license to the new company X. Verify this company is not visible on Admin
- verify another user is able to register for the company X and has the feats of the corresponding license
- broadcaster should only be able to set prices
- sales should only be able to create licenses
- producer and distributor should be able to do everything
- verify it is possible to add the company which is not in TMDB via licensing and later register a user for it
- verify it is not possible to register for the already approved company
-  other corner cases and security threats
Known issue: registration grieving. Given there is a pending company registration, malicious (or just other) user may submit registration for the same company and thus override the previous registration request.

## Links to relevant issues or information

Closes #151 
Closes #127

### CODE REVIEW

**Comment by troggy** [comment]
@mwaa this one fixes both #127 and #151

**Comment by troggy** [comment]
before merging, requires https://github.com/WhiteRabbitTheWorldIsYours/dashboard/pull/189 to be merged first

**Comment by troggy** [comment]
@mwaa just rebased on `master` and force pushed

**Comment by mwaa** [comment]
@troggy can't test process completely. 
On the add sublicense form getting validation error `Company is not selected` even when i have selected a company

**Review by mwaa — APPROVED** [review]

**Pull request merged**
