### PR TITLE
Add restriction to use IMDB

### LINKED ISSUE #48: Reconcile imdb id
## Scope

Please note tt2380307 is not the same movie as 2380307. 
`tt {int}` IMDB ID
`plain int` TMDB API ID

Coco 2017 Animation
For the public website [tt2380307 ](https://www.imdb.com/title/tt2380307) will have `tt` but api will never have this with equivalent api id `354912`

tt2380307 is still valid though we would have to check for api id to avoid duplicates of the same movie against TMDB api 354912.

## Deliverable
- restrict to using tt2380307 since this available to public. retrieve value from api
- add validation check that record with TMDB id does not exist before insert using IMDB id
- if IMDB id is missing then save record using TMDB ID with source will change to `TMDB` instead of IMDB change BE to account for this

## Roles
gardener: @mwaa 50 DAI
worker: @mwaa 80%
reviewer: [reviewer] 20%

### LINKED ISSUE #60: incorrect IMDB ID inserted through movie addition
The IMDB ID added through the movie addition screen seems incorrect.

Example: 
Broken Flowers has IMDB ID tt0412019. It gets assigned ID 308. 
image

### PR DESCRIPTION
**Pull request by mwaa**
Please remember the [Contributing Guidelines](https://WhiteRabbitTheWorldIsYours/dashboard/blob/master/CONTRIBUTION.md) :heart:

## What does this PR do?
Fix to use IMDB ID always instead of TMDB 

## Recommendations for testing
- [x] Both frontend and backend `npm link @whiterabbitjs/dashboard-common`
- [x] Movie search and click select and display selection prefills IMDB correctly
- [x] TMDB id and IMDB are stored
- [x] Prevent saving movie record for movies without IMDB 
- [x] Notification displayed for movies without IMDB ID

## Links to relevant issues or information
Closes #60 
Closes #48

### CODE REVIEW

**Comment by mwaa** [comment]
Not sure about `Prevent saving movie record for movies without IMDB`. Looking for comments from reviewer

**Comment by Clearwood** [comment]
image
I am getting a crash when trying to search for the movie with title `rams`

**Comment by mwaa** [comment]
@Clearwood checking availability of release date before pushing slicing year

**Comment by troggy** [comment]
> Prevent saving movie record for movies without IMDB

which movie can I use to test this?

**Comment by troggy** [comment]
This works great. Tested by adding a movie + pricing for it (had to fix the link of the movie list) → with https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/pull/119 the price was shown nicely (except https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/84 is still a problem). Sent payment, it got reflected in the revenue 👌

**Comment by troggy** [comment]
well.. search by IMDB has some problems.. looking

**Comment by mwaa** [comment]
> > Prevent saving movie record for movies without IMDB
> 
> which movie can I use to test this?

`Puppy's First Year` has no imbd_id and no crew nor cast

**Pull request merged**
